[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_guide_size = 1
    let g:indent_guides_auto_colors = 0
    "autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=3
    "autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=4
'''

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
    let g:jellybeans_overrides = {
\   'Todo': { 'guifg': '303030', 'guibg': 'f0f000', 
\   'ctermfg': 'Black', 'ctermbg': 'Yellow', 
\   'attr': 'bold' },}
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \    'colorscheme': 'wombat',
    \}
'''
