set -g prefix C-a
unbind C-b
bind C-a send-prefix
bind | split-window -h
bind - split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind -r C-o rotate-window

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

setw -g window-status-style fg=cyan,bg=default,dim
setw -g window-status-current-style fg=white,bg=red,bright

set -g pane-border-style fg=green,bg=black
set -g pane-active-border-style fg=white,bg=yellow

set -g message-style fg=white,bg=black,bright

setw -g monitor-activity on
set -g visual-activity on

setw -g mode-keys vi
#set-option -g default-command "reattach-to-user-namespace -l bash"

set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'
